# Licensed under the Apache-2.0 license

[bitstream]
name = "core-2.0"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_2fe48aa8.pdi"
hash = "ae9b0ea6dc3196b64c53c1b3c3f9c3c09534acd127f971b76898a8edbfde665e"
caliptra_variant = "core"
caliptra_rtl_commit = "22f402e4858c198ac45541ecc9e14f471d0d0fd5"

