# Licensed under the Apache-2.0 license

[bitstream]
name = "core-2.0"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_19d0f1b7.pdi"
hash = "0949eeaa910e8faf700c2fd3d96c69fdba606397c0b22adc759d6880756e4ed5"
caliptra_variant = "core"
caliptra_rtl_commit = "19d0f1b739ec65e0cfc344734a0b0aaf480066b8"

