# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.1"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_89e19cf7.pdi"
hash = "84e2e223c61bb8fadb392451379e9882b703b0e7b940d462933a47eda6772fae"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "2b7c4bf60cde3101c4287d31213164d1767ce33e"

