# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.1"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_33b959ea.pdi"
hash = "ae9097dc22c10bf919599573c8fb25a074d926d8e922df9bf74ccdbca05b07e8"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "33b959ea4990783e79cd5d463adc0c1e4dad0298"

