# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.0"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_957411dd.pdi"
hash = "b44c743fc8b9259789da2e0aa38cff4345a78bdd6b01e33e67a83333bf17142f"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "794bbb22f800ce3b028c21d7cfc9fbc1b2c2f1d3a9f15d3af35a4100634ff14e"

