# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.0"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_7e530bcc.pdi"
hash = "faeeb86252a45f4cae23ee91a15402598e2d0d9c6fd1ea7d489e7290e3a97efc"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "794bbb22f800ce3b028c21d7cfc9fbc1b2c2f1d3a9f15d3af35a4100634ff14e"

