# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.1"
url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/scratch/runtime_e13b87a3.pdi"
hash = "cf9106313a78118e47a4638f8b386ce27da3500193b89d9eccd17c83cd0f339b"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "2b7c4bf60cde3101c4287d31213164d1767ce33e"

