# Licensed under the Apache-2.0 license

[package]
name = "caliptra_registers_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureg-codegen.workspace = true
ureg-schema.workspace = true
ureg-systemrdl.workspace = true
caliptra-systemrdl.workspace = true
quote.workspace = true