[package]
name = "caliptra-emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.14", default-features = false, features = ["std"] }
caliptra-emu-bus = { path = "../lib/bus" }
caliptra-emu-cpu = { path = "../lib/cpu" }
caliptra-emu-periph = { path = "../lib/periph" }
caliptra-emu-types = { path = "../lib/types" }
