# Licensed under the Apache-2.0 license.

[package]
name = "caliptra-image-serde"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
caliptra-image-types = { workspace = true, features = ["std"] }
zerocopy.workspace = true
memoffset.workspace = true

