# Licensed under the Apache-2.0 license

[package]
name = "caliptra-image-fake-keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caliptra-image-gen = { path = "../gen" }
caliptra-image-types = { path = "../types" }
caliptra-lms-types = { path = "../../lms-types" }
zerocopy = "0.6.1"

[dev-dependencies]
caliptra-image-openssl = { path = "../openssl" }