# Licensed under the Apache-2.0 license

[alias]
xtask = "run --package xtask --"
xtask-fpga = "run --package xtask --features=fpga_realtime --"
xtask-subsystem = "run --package xtask --features=fpga_subsystem --"

[env]
RUST_MIN_STACK="16777216" # 16MB

[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "target-feature=+relax",
  "-C", "target-feature=+unaligned-scalar-mem",
  "-C", "target-feature=+zba",
  "-C", "target-feature=+zbb",
  "-C", "target-feature=+zbc",
  "-C", "target-feature=+zbs",
]
