# Licensed under the Apache-2.0 license

[package]
name = "caliptra-drivers"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
caliptra-lms-types = { path = "../lms-types" }
caliptra-registers = { path = "../registers" }
ureg = { path = "../ureg" }
zerocopy = "0.6.1"
cfg-if = "1.0.0"
bitfield = "0.14.0"
bitflags = "2.0.1"
caliptra-error = { version = "0.1.0", path = "../error" , default-features=false}

[features]
emu = []
itrng = ["caliptra-hw-model/itrng"]
verilator = ["caliptra-hw-model/verilator"]
fpga_realtime = ["caliptra-hw-model/fpga_realtime"]

[dev-dependencies]
caliptra-drivers-test-bin = { path = "test-fw" }
caliptra-hw-model = { path = "../hw-model" }
caliptra-hw-model-types = { path = "../hw-model/types" }
caliptra-builder = { path = "../builder" }
caliptra-test = { path = "../test" }
openssl = { version = "0.10", features = ["vendored"] }