# Licensed under the Apache-2.0 license

[package]
name = "test-printer"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = { version = "0.31.0", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.4.18", features = ["derive"] }