# Licensed under the Apache-2.0 license

[package]
name = "caliptra-cfi-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
doctest = false

[dependencies]
syn.workspace = true
quote = "1.0.23"
proc-macro2 = "1.0.51"
paste = "1.0.11"
