# Licensed under the Apache-2.0 license

[package]
name = "caliptra-image-elf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
caliptra-image-gen.workspace = true
caliptra-image-types.workspace = true
elf.workspace = true

[lints]
workspace = true
