name: Build FPGA SD image for caliptra-1.x

on:
  pull_request:
    paths:
      - ".github/workflows/fpga-image-1.x.yml"

  schedule:
    # 5:13 AM PST tuesday, thursday
    - cron: '13 13 * * 2,4'

  workflow_call:
  workflow_dispatch:

jobs:
  build_sd_image:
    name: Build 1.x FPGA images
    uses: chipsalliance/caliptra-sw/.github/workflows/fpga-image.yml@caliptra-1.x
    with:
      branch: "caliptra-1.x"
