name: Build FPGA SD image for caliptra-2.0

on:
  pull_request:
    paths:
      - ".github/workflows/fpga-image-2.x.yml"

  schedule:
    # 5:13 AM PST tuesday, thursday
    - cron: '13 13 * * 2,4'

  workflow_call:
  workflow_dispatch:

jobs:
  build_sd_image:
    name: Build 2.x images
    uses: chipsalliance/caliptra-sw/.github/workflows/fpga-image.yml@caliptra-2.0
    with:
      branch: "caliptra-2.0"
