# Licensed under the Apache-2.0 license

[package]
name = "caliptra-rom-test-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
caliptra-cpu.workspace = true
caliptra-drivers.workspace = true
caliptra-registers.workspace = true
ufmt.workspace = true

[build-dependencies]
cfg-if.workspace = true

[features]
default = ["std"]
emu = ["caliptra-drivers/emu"]
riscv = ["caliptra-cpu/riscv"]
std = ["ufmt/std"]
